/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from 'kysely';

export type AlbumTypeEnum = 'album' | 'compilation' | 'single';

export type ArtistRoleEnum = 'featured' | 'main';

export type CancellationReasonEnum =
    | 'account_deleted'
    | 'admin_cancelled'
    | 'expired_naturally'
    | 'fraud_suspected'
    | 'other'
    | 'payment_failed'
    | 'user_cancelled';

export type FriendshipStatusEnum = 'accepted' | 'blocked' | 'declined' | 'pending';

export type Generated<T> =
    T extends ColumnType<infer S, infer I, infer U>
        ? ColumnType<S, I | undefined, U>
        : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
    [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Numeric = ColumnType<string, number | string, number | string>;

export type ReleaseDatePrecisionEnum = 'day' | 'month' | 'year';

export type SubscriptionStatusEnum = 'active' | 'cancelled' | 'expired';

export type SubscriptionTypeEnum = 'annual' | 'lifetime' | 'monthly' | 'quarterly' | 'semiannual';

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface AlbumArtists {
    albumId: number;
    artistId: number;
    artistRole: Generated<ArtistRoleEnum>;
}

export interface Albums {
    albumId: Generated<number>;
    albumName: string;
    albumType: AlbumTypeEnum;
    createdAt: Generated<Timestamp>;
    ean: string | null;
    externalUrl: string;
    imageUri: string | null;
    popularity: number;
    releaseDate: Timestamp;
    releaseDatePrecision: ReleaseDatePrecisionEnum;
    spotifyId: string;
    spotifyUri: string;
    totalTracks: number;
    upc: string | null;
}

export interface ArtistGenres {
    artistId: number;
    genreId: number;
}

export interface Artists {
    artistId: Generated<number>;
    artistName: string;
    createdAt: Generated<Timestamp>;
    externalUrl: string;
    followers: Generated<number>;
    imageUri: string | null;
    popularity: number;
    spotifyId: string;
    spotifyUri: string;
}

export interface Friendships {
    createdAt: Generated<Timestamp>;
    friendshipId: Generated<number>;
    status: Generated<FriendshipStatusEnum>;
    updatedAt: Generated<Timestamp>;
    userId1: number;
    userId2: number;
}

export interface Genres {
    createdAt: Generated<Timestamp>;
    genreId: Generated<number>;
    genreName: string;
}

export interface ListeningHistory {
    backfilled: Generated<boolean>;
    createdAt: Generated<Timestamp>;
    endedAt: Timestamp;
    historyId: Generated<Int8>;
    incognito: Generated<boolean>;
    msPlayed: number;
    offline: Generated<boolean>;
    skipped: Generated<boolean>;
    trackId: number;
    userId: number;
}

export interface ListeningHistoryRaw {
    connCountry: string | null;
    historyId: Int8;
    offlineTimestamp: Int8 | null;
    platform: string | null;
    rawTs: Timestamp | null;
    reasonEnd: string | null;
    reasonStart: string | null;
    shuffle: boolean | null;
}

export interface TrackArtists {
    artistId: number;
    artistRole: Generated<ArtistRoleEnum>;
    trackId: number;
}

export interface TrackAudioFeatures {
    acousticness: Numeric;
    createdAt: Generated<Timestamp>;
    danceability: Numeric;
    energy: Numeric;
    instrumentalness: Numeric;
    key: number;
    liveness: Numeric;
    loudness: Numeric;
    mode: number;
    speechiness: Numeric;
    tempo: Numeric;
    timeSignature: number;
    trackId: number;
    valence: Numeric;
}

export interface Tracks {
    albumId: number;
    createdAt: Generated<Timestamp>;
    discNumber: number;
    durationMs: number;
    explicit: boolean;
    externalUrl: string | null;
    imageUri: string | null;
    isLocal: Generated<boolean>;
    isrc: string | null;
    popularity: number;
    spotifyId: string | null;
    spotifyUri: string | null;
    trackId: Generated<number>;
    trackName: string;
    trackNumber: number;
}

export interface UserPrivacySettings {
    currentlyPlaying: Generated<boolean>;
    friends: Generated<boolean>;
    isPrivate: Generated<boolean>;
    recentlyPlayed: Generated<boolean>;
    streams: Generated<boolean>;
    streamStats: Generated<boolean>;
    topAlbums: Generated<boolean>;
    topArtists: Generated<boolean>;
    topGenres: Generated<boolean>;
    topTracks: Generated<boolean>;
    updatedAt: Generated<Timestamp>;
    userId: number;
}

export interface UserProfiles {
    avatarUri: string | null;
    bio: string | null;
    location: string | null;
    timezone: Generated<string | null>;
    timezoneUpdatedAt: Timestamp | null;
    updatedAt: Generated<Timestamp>;
    userId: number;
    userPreferences: Generated<Json>;
}

export interface Users {
    createdAt: Generated<Timestamp>;
    email: string;
    isVerified: Generated<boolean>;
    name: string;
    passwordHash: string;
    passwordSalt: string;
    updatedAt: Generated<Timestamp>;
    userId: Generated<number>;
    username: string;
}

export interface UserSpotifyData {
    accessToken: string | null;
    fullHistoryImported: Generated<boolean>;
    historyImportedAt: Timestamp | null;
    lastFetchedAt: Timestamp | null;
    refreshToken: string | null;
    revokedAt: Timestamp | null;
    spotifyDisplayName: string | null;
    spotifyUserId: string | null;
    tokenExpiresAt: Timestamp | null;
    userId: number;
}

export interface UserSubscriptions {
    autoRenewal: Generated<boolean>;
    cancellationReason: CancellationReasonEnum | null;
    cancelledAt: Timestamp | null;
    nextBillingDate: Timestamp | null;
    subscribedAt: Timestamp;
    subscriptionEnds: Timestamp | null;
    subscriptionId: Generated<number>;
    subscriptionStatus: Generated<SubscriptionStatusEnum>;
    subscriptionType: SubscriptionTypeEnum;
    userId: number | null;
    userIdSnapshot: number;
}

export interface DB {
    albumArtists: AlbumArtists;
    albums: Albums;
    artistGenres: ArtistGenres;
    artists: Artists;
    friendships: Friendships;
    genres: Genres;
    listeningHistory: ListeningHistory;
    listeningHistoryRaw: ListeningHistoryRaw;
    trackArtists: TrackArtists;
    trackAudioFeatures: TrackAudioFeatures;
    tracks: Tracks;
    userPrivacySettings: UserPrivacySettings;
    userProfiles: UserProfiles;
    users: Users;
    userSpotifyData: UserSpotifyData;
    userSubscriptions: UserSubscriptions;
}
