BEGIN;

ALTER TABLE listening_history
    ADD COLUMN offline BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN offline_synced_at TIMESTAMPTZ DEFAULT NULL,
    ADD COLUMN created_at TIMESTAMPTZ NOT NULL DEFAULT NOW();

COMMIT;